### ISSUE TITLE
Fails on Darwin

### ISSUE THREAD

**Issue by uhlhosting** [virtual-kubelet/openstack-zun#9]
Running darwin, any idea why this fails?

`./virtual-kubelet     
ERRO[0001] TLS certificates not provided, not setting up pod http server  certPath= keyPath= node=virtual-kubelet operatingSystem=Linux provider= watchedNamespace=
INFO[0001] Initialized                                   node=virtual-kubelet operatingSystem=Linux provider= watchedNamespace=
INFO[0001] Pod cache in-sync                             node=virtual-kubelet operatingSystem=Linux provider= watchedNamespace=
INFO[0001] starting workers                              node=virtual-kubelet operatingSystem=Linux provider= watchedNamespace=
INFO[0001] started workers                               node=virtual-kubelet operatingSystem=Linux provider= watchedNamespace=
E0410 02:11:29.650485   95898 runtime.go:69] Observed a panic: "assignment to entry in nil map" (assignment to entry in nil map)
/Users/cosmic/Go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/runtime/runtime.go:76
/Users/cosmic/Go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/runtime/runtime.go:65
/Users/cosmic/Go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/runtime/runtime.go:51
/usr/local/Cellar/go/1.14.1/libexec/src/runtime/panic.go:967
/usr/local/Cellar/go/1.14.1/libexec/src/runtime/map_faststr.go:204
/Users/cosmic/Go/src/github.com/virtual-kubelet/openstack-zun/zun.go:203
/Users/cosmic/Go/src/github.com/virtual-kubelet/openstack-zun/zun.go:153
/Users/cosmic/Go/pkg/mod/github.com/virtual-kubelet/virtual-kubelet@v0.10.0/node/pod.go:85
/Users/cosmic/Go/pkg/mod/github.com/virtual-kubelet/virtual-kubelet@v0.10.0/node/podcontroller.go:321
/Users/cosmic/Go/pkg/mod/github.com/virtual-kubelet/virtual-kubelet@v0.10.0/node/podcontroller.go:292
/Users/cosmic/Go/pkg/mod/github.com/virtual-kubelet/virtual-kubelet@v0.10.0/node/queue.go:69
/Users/cosmic/Go/pkg/mod/github.com/virtual-kubelet/virtual-kubelet@v0.10.0/node/queue.go:83
/Users/cosmic/Go/pkg/mod/github.com/virtual-kubelet/virtual-kubelet@v0.10.0/node/podcontroller.go:253
/Users/cosmic/Go/pkg/mod/github.com/virtual-kubelet/virtual-kubelet@v0.10.0/node/podcontroller.go:240
/Users/cosmic/Go/pkg/mod/github.com/virtual-kubelet/virtual-kubelet@v0.10.0/node/podcontroller.go:218
/Users/cosmic/Go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:152
/Users/cosmic/Go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:153
/Users/cosmic/Go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:88
/usr/local/Cellar/go/1.14.1/libexec/src/runtime/asm_amd64.s:1373
panic: assignment to entry in nil map [recovered]
	panic: assignment to entry in nil map

goroutine 242 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/Users/cosmic/Go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/runtime/runtime.go:58 +0x105
panic(0x1f7f300, 0x232f2f0)
	/usr/local/Cellar/go/1.14.1/libexec/src/runtime/panic.go:967 +0x166
github.com/virtual-kubelet/openstack-zun.(*ZunProvider).getContainers(0xc000514900, 0x2380fa0, 0xc000785a40, 0xc0007d8a80, 0x1, 0xc0006b5980, 0x32, 0xc0004e6880, 0x3e)
	/Users/cosmic/Go/src/github.com/virtual-kubelet/openstack-zun/zun.go:203 +0x4ab
github.com/virtual-kubelet/openstack-zun.(*ZunProvider).CreatePod(0xc000514900, 0x2380fa0, 0xc000785a40, 0xc0007d8a80, 0xb, 0xc0006b5980)
	/Users/cosmic/Go/src/github.com/virtual-kubelet/openstack-zun/zun.go:153 +0x420
github.com/virtual-kubelet/virtual-kubelet/node.(*PodController).createOrUpdatePod(0xc0000c2ae0, 0x2380fa0, 0xc000785a40, 0xc0007d8a80, 0x0, 0x0)
	/Users/cosmic/Go/pkg/mod/github.com/virtual-kubelet/virtual-kubelet@v0.10.0/node/pod.go:85 +0x753
github.com/virtual-kubelet/virtual-kubelet/node.(*PodController).syncPodInProvider(0xc0000c2ae0, 0x2380fa0, 0xc000784e10, 0xc0007d8a80, 0x0, 0x0)
	/Users/cosmic/Go/pkg/mod/github.com/virtual-kubelet/virtual-kubelet@v0.10.0/node/podcontroller.go:321 +0x330
github.com/virtual-kubelet/virtual-kubelet/node.(*PodController).syncHandler(0xc0000c2ae0, 0x2380fa0, 0xc000784e10, 0xc0006b5bc0, 0x3e, 0x0, 0x0)
	/Users/cosmic/Go/pkg/mod/github.com/virtual-kubelet/virtual-kubelet@v0.10.0/node/podcontroller.go:292 +0x7ed
github.com/virtual-kubelet/virtual-kubelet/node.handleQueueItem.func1(0xc000f1fd40, 0x2393180, 0xc0000f52e0, 0x2386aa0, 0xc0003c3260, 0xc000f0cda0, 0x1f0e920, 0xc0004a4070, 0x0, 0x0)
	/Users/cosmic/Go/pkg/mod/github.com/virtual-kubelet/virtual-kubelet@v0.10.0/node/queue.go:69 +0x235
github.com/virtual-kubelet/virtual-kubelet/node.handleQueueItem(0x2380fa0, 0xc000784a50, 0x2393180, 0xc0000f52e0, 0xc000f0cda0, 0x1f0e900)
	/Users/cosmic/Go/pkg/mod/github.com/virtual-kubelet/virtual-kubelet@v0.10.0/node/queue.go:83 +0x1f6
github.com/virtual-kubelet/virtual-kubelet/node.(*PodController).processNextWorkItem(0xc0000c2ae0, 0x2380fa0, 0xc0007845d0, 0x21c12c3, 0x2, 0x2393180, 0xc0000f52e0, 0x0)
	/Users/cosmic/Go/pkg/mod/github.com/virtual-kubelet/virtual-kubelet@v0.10.0/node/podcontroller.go:253 +0x18e
github.com/virtual-kubelet/virtual-kubelet/node.(*PodController).runWorker(0xc0000c2ae0, 0x2380fa0, 0xc00069d320, 0x21c12c3, 0x2, 0x2393180, 0xc0000f52e0)
	/Users/cosmic/Go/pkg/mod/github.com/virtual-kubelet/virtual-kubelet@v0.10.0/node/podcontroller.go:240 +0x6a
github.com/virtual-kubelet/virtual-kubelet/node.(*PodController).Run.func4()
	/Users/cosmic/Go/pkg/mod/github.com/virtual-kubelet/virtual-kubelet@v0.10.0/node/podcontroller.go:218 +0xb1
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0003bd640)
	/Users/cosmic/Go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0003bd640, 0x3b9aca00, 0x0, 0x1, 0xc000668540)
	/Users/cosmic/Go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc0003bd640, 0x3b9aca00, 0xc000668540)
	/Users/cosmic/Go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:88 +0x4d
created by github.com/virtual-kubelet/virtual-kubelet/node.(*PodController).Run
	/Users/cosmic/Go/pkg/mod/github.com/virtual-kubelet/virtual-kubelet@v0.10.0/node/podcontroller.go:216 +0x93e
zsh: exit 2     ./virtual-kubelet
2:11:29 [cosmic:~/Go/src/github.com/virtual-kubelet/openstack-zun/bin] master 2 ± 
`

**Comment by hongbin** [comment]
@uhlhosting I couldn't reproduce this issue. Which commit you were based on? Do you hit the same issue on latest master version? If you do, how to reproduce it?
